export const theme = {
  color_key: '#1D2A3D',
  color_keyWhite: '#F9FAFB',
  color_textBlack: '#111111',
  color_textKey: '#263747',
  color_textWhite: '#FFFFFF',
  color_textGray: '#909090',
  color_textRed: '#EB1E1E',
  color_bgWhite: '#FFFFFF',
  color_bgLightGray: '#E1E1E1',
  color_borderGray: '#EAEAEA',
  fontSize_xs: '10px',
  fontSize_sm: '12px',
  fontSize_base: '14px',
  fontSize_md: '16px',
  fontSize_lg: '18px',
  fontSize_xl: '20px',
  shadow: 'rgba(0, 0, 0, 0.06) 0px 4px 40px 0px',
} as const;
