export const theme = {
  color_key: "#1D2A3D",
  color_keyWhite: "#F9FAFB",
  color_textBlack: "#111111",
  color_textKey: "#263747",
  color_textWhite: "#FFFFFF",
  color_textGray: "#909090",
  color_textRed: "#EB1E1E",
  color_bgWhite: "#FFFFFF",
  color_bgLightGray: "#E1E1E1",
  color_borderGray: "#EAEAEA",
  fontSize: {
    xs: "10px",
    sm: "12px",
    base: "14px",
    md: "16px",
    lg: "18px",
    xl: "20px",
  },
} as const;
